# Generated by Django 3.2.9 on 2021-11-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('user_name', models.TextField()),
                ('password', models.TextField()),
                ('birthday', models.DateTimeField()),
                ('phone_number', models.IntegerField()),
                ('point', models.IntegerField()),
                ('total_fee', models.IntegerField()),
            ],
        ),
    ]
