# Generated by Django 3.2.9 on 2021-11-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('car_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('car_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('parking_slot_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('floor', models.IntegerField()),
                ('section', models.IntegerField()),
                ('number', models.IntegerField()),
                ('slot_state', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'parking_slot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('parking_slot_id', models.CharField(max_length=20)),
                ('reservation_date', models.DateField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('state', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=30)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('point', models.IntegerField(blank=True, null=True)),
                ('total_fee', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
