export const parkingLotData = [
  [
    { slotID: "1", state: "-1", floor: "B1" },
    { slotID: "2", state: "3", floor: "B1" },
    { slotID: "3", state: "2", floor: "B1" },
    { slotID: "4", state: "2", floor: "B1" },
    { slotID: "5", state: "2", floor: "B1" },
    { slotID: "6", state: "2", floor: "B1" },
    { slotID: "7", state: "3", floor: "B1" },
    { slotID: "8", state: "3", floor: "B1" },
    { slotID: "9", state: "3", floor: "B1" },
    { slotID: "10", state: "-1", floor: "B1" },
  ],
  [
    { slotID: "1", state: "3", floor: "B1" },
    { slotID: "2", state: "-1", floor: "B1" },
    { slotID: "3", state: "-1", floor: "B1" },
    { slotID: "4", state: "-1", floor: "B1" },
    { slotID: "5", state: "-1", floor: "B1" },
    { slotID: "6", state: "-1", floor: "B1" },
    { slotID: "7", state: "-1", floor: "B1" },
    { slotID: "8", state: "-1", floor: "B1" },
    { slotID: "9", state: "-1", floor: "B1" },
    { slotID: "10", state: "0", floor: "B1" },
  ],
  [
    { slotID: "1", state: "3", floor: "B1" },
    { slotID: "2", state: "-1", floor: "B1" },
    { slotID: "3", state: "1", floor: "B1" },
    { slotID: "4", state: "3", floor: "B1" },
    { slotID: "5", state: "3", floor: "B1" },
    { slotID: "6", state: "2", floor: "B1" },
    { slotID: "7", state: "2", floor: "B1" },
    { slotID: "8", state: "2", floor: "B1" },
    { slotID: "9", state: "-1", floor: "B1" },
    { slotID: "10", state: "0", floor: "B1" },
  ],
  [
    { slotID: "1", state: "2", floor: "B1" },
    { slotID: "2", state: "-1", floor: "B1" },
    { slotID: "3", state: "-1", floor: "B1" },
    { slotID: "4", state: "-1", floor: "B1" },
    { slotID: "5", state: "-1", floor: "B1" },
    { slotID: "6", state: "-1", floor: "B1" },
    { slotID: "7", state: "-1", floor: "B1" },
    { slotID: "8", state: "-1", floor: "B1" },
    { slotID: "9", state: "-1", floor: "B1" },
    { slotID: "10", state: "0", floor: "B1" },
  ],
  [
    { slotID: "1", state: "-1", floor: "B1" },
    { slotID: "2", state: "3", floor: "B1" },
    { slotID: "3", state: "3", floor: "B1" },
    { slotID: "4", state: "1", floor: "B1" },
    { slotID: "5", state: "3", floor: "B1" },
    { slotID: "6", state: "3", floor: "B1" },
    { slotID: "7", state: "-1", floor: "B1" },
    { slotID: "8", state: "-1", floor: "B1" },
    { slotID: "9", state: "2", floor: "B1" },
    { slotID: "10", state: "-1", floor: "B1" },
  ],
];
